export const COUNTER_ACTION_TYPES = {
  INCREMENT: 'counter/INCREMENT',
  DECREMENT: 'counter/DECREMENT',
  SET_COUNT: 'counter/SET_COUNT',
  RESET_COUNT: 'counter/RESET_COUNT',

  //Async Actions
  SET_COUNT_START: 'counter/SET_COUNT_START',
  SET_COUNT_SUCCESS: 'counter/SET_COUNT_SUCCESS',
  SET_COUNT_FAILURE: 'counter/SET_COUNT_FAILURE',
};
